### ISSUE TITLE
Add track info in dump reader

### ISSUE THREAD

**Issue by hpwit** [hpwit/SID6581#2]
Add function to get the track information when paying file from Sid register
sid.play()

**Comment by hpwit** [comment]
char * getSongName();
    int getSongNumber();
    int getPlaylistSize();
added

**Comment by tobozo** [comment]
great ^^

since those methods only apply to the *cpu* object, the *sid* object still needs the equivalent methods, or at least have the means to get the same information from a dump.txt file

the easiest way I've found so far is to move those properties from "protected" to "public" in SID6581.h

```C
    int numberToPlay=0;
    songstruct listsongs[80];
```

and doing this from my sketch:

```C
    if( sid.numberToPlay != numberToPlay ) {
      numberToPlay = sid.numberToPlay;
      songstruct p;
      p = sid.listsongs[sid.numberToPlay];
      sprintf( fileName, "%s", p.filename );
      // print the filename to TFT and Serial
    }
```

**Comment by hpwit** [comment]
I have done it from both
but not pushed on the git for now
